- name: Connect to other system
  hosts: dev1060system
  remote_user: dev1060

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      become: yes
    - name: Install FFmpeg
      apt:
        name: ffmpeg
        state: present
      become: yes